### ISSUE TITLE
in IOS 13, Sign in to null

### ISSUE THREAD

**Issue by JayChew** [SocialiteProviders/Apple#1]
For users whose iPhone is support Sign in With Apple, It show Do you want to sign in to null with your Apple ID xxxx@example.com

**Comment by Ahilmurugesan** [comment]
Please ensure that client credentials and service accounts are properly configured and passed on to the apple API.

**Comment by Ahilmurugesan** [comment]
Please kindly close the ticket if you feel the response is useful.

**Comment by JayChew** [comment]
> Please ensure that client credentials and service accounts are properly configured and passed on to the apple API.

Basiclly, users click Sign in With Apple button in website, and then redirect to https://appleid.apple.com/auth/authorize to key in Apple ID and password to sign in.
Client ID, Client Secret, Auth Key, Redirect, Team ID, Key ID are correct.

![image](https://user-images.githubusercontent.com/22468507/83319383-96e75000-a270-11ea-800e-095ca3adc4f6.png)
And here is the output normally

![Image from iOS](https://user-images.githubusercontent.com/22468507/83319505-af0b9f00-a271-11ea-83f7-bc405789f495.png)
And here is the output to those users who using latest iPhone (IOS 13).

So, I am not sure what else is miss to to solve the problem? Thank

**Comment by prajwalsprakash** [comment]
@JayChew try this:
https://stackoverflow.com/questions/60000640/sign-in-with-apple-missing-app-name-in-the-permission-message

**Comment by JayChew** [comment]
> @JayChew try this:
> https://stackoverflow.com/questions/60000640/sign-in-with-apple-missing-app-name-in-the-permission-message

I had went through this link, the solution is only work for mobile app. And it try Sign in with Apple using Auth0, but it didn't mentioned request from mobile-app or website.

Since my project had implemented Sign in With Apple for mobile app and Sign in With Apple for website. So, for Sign in With Apple for mobile app implementation, Client ID is equal to App ID and no need Redirect uri value. For Sign in With Apple for website implementation, Client ID is equal to Service ID. 

So the problem is only those users who using latest iPhone (IOS 13), will see "Do you want to sign in to null with your Apple ID" in the result of Sign in with Apple on website login page.
